spring:
  application:
    name: ABC-SERVICE

server:
  port: 5555

  # -- Configure for Ribbon:


application:
  client:
    url: http://localhost:6666

ping-server:
  ribbon:
    eureka:
      enabled: false # Disable Default Ping
    listOfServers: localhost:8000,localhost:8001,localhost:8002,localhost:8004,localhost:8003, localhost:8005
    ServerListRefreshInterval: 15000

  # -- Configure Discovery Client (Eureka Client).
  # Configure this application to known "Service Registration".

eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is an instance of XYZ-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://my-eureka-server.com:9000/eureka
      defaultZone: http://my-eureka-server-us.com:9001/eureka
#      defaultZone: http://my-eureka-server-fr.com:9002/eureka
#      defaultZone: http://my-eureka-server-vn.com:9003/eureka